development:
  adapter: postgresql
  encoding: unicode
  database: payback_development
  pool: 5
  username: payback
  password: R1269mrFno

test:
  adapter: postgresql
  encoding: unicode
  database: payback_test
  pool: 5
  username: payback
  password: R1269mrFno

production:
  adapter: postgresql
  encoding: unicode
  database: payback_production
  pool: 5
  username: payback
  password: R1269mrFno
